[package]
name = "gherkin_rust"
version = "0.8.4"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
description = "A pure Rust implementation of the Gherkin (`.feature` file) language for the Cucumber testing framework"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/bbqsrc/gherkin-rust"
documentation = "https://docs.rs/gherkin_rust"
homepage = "https://github.com/bbqsrc/gherkin-rust"
edition = "2018"

[[test]]
name = "cucumber"
harness = false

[dependencies]
textwrap = "0.12.1"
peg = "0.6.3"
typed-builder = "0.7.0"
thiserror = "1.0.20"

[dev-dependencies]
cucumber = { package = "cucumber_rust", version = "^0.8.0" }
async-trait = "0.1.40"
futures = "0.3.5"
